#!/usr/bin/env python3
"""
Standalone Python/Matplotlib recreation generated by MathRecon Engine.
"""
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.patches as patches
import math

def draw_diagram():
    fig, ax = plt.subplots(figsize=(6.5, 4.8), dpi=300)
    ax.set_aspect('equal')
    ax.axis('off')

    # Parabola: parabola_main
    xs = np.linspace(-2.7, 2.75, 100)
    ys = 0.38 * (xs**2) + 0.0 * xs + 0.0
    ax.plot(xs, ys, color='#111111', linewidth=2.4, zorder=2)
    ax.annotate('', xy=(xs[0], ys[0]), xytext=(xs[3], ys[3]),
                arrowprops=dict(arrowstyle='-|>', lw=2.4, color='#111111', mutation_scale=16))
    ax.annotate('', xy=(xs[-1], ys[-1]), xytext=(xs[-4], ys[-4]),
                arrowprops=dict(arrowstyle='-|>', lw=2.4, color='#111111', mutation_scale=16))

    # Segment: secant_line
    ax.plot([-1.900, 2.450], [-1.769, 2.281], color='#111111', linewidth=2.2, zorder=2)

    # Segment: vertical_stem
    ax.plot([0.000, 0.000], [2.281, -0.000], color='#111111', linewidth=2.0, zorder=2)

    # Segment: top_horizontal_m
    ax.plot([0.000, 2.450], [2.281, 2.281], color='#111111', linewidth=2.0, zorder=2)

    # Segment: left_horizontal_b
    ax.plot([-1.950, 0.000], [1.445, 1.445], color='#111111', linewidth=2.0, zorder=2)

    # Segment: left_chord
    ax.plot([-1.950, 0.000], [1.445, -0.000], color='#111111', linewidth=2.0, zorder=2)

    # Segment: left_drop
    ax.plot([-0.750, -0.750], [1.445, 0.556], color='#111111', linewidth=1.8, zorder=2)

    # Right Angle: ra_top
    ax.plot([0.261, 0.261, 0.000], [2.281, 2.035, 2.035], color='#000000', linewidth=1.6, zorder=2)

    # Right Angle: ra_left
    ax.plot([-0.982, -0.982, -0.750], [1.445, 1.226, 1.226], color='#000000', linewidth=1.6, zorder=2)

    # Arc Angle: arc_A
    arc_arc_A = patches.Arc((0.000, -0.000), 1.758, 1.758, angle=0, theta1=43.0, theta2=90.0, color='#000000', linewidth=1.6, zorder=2)
    ax.add_patch(arc_arc_A)

    # Arc Angle: arc_B
    arc_arc_B = patches.Arc((-1.950, 1.445), 1.034, 1.034, angle=0, theta1=-36.5, theta2=0.0, color='#000000', linewidth=1.6, zorder=2)
    ax.add_patch(arc_arc_B)

    # Arc Angle: arc_C
    arc_arc_C = patches.Arc((0.000, -0.000), 1.499, 1.499, angle=0, theta1=143.5, theta2=223.0, color='#000000', linewidth=1.6, zorder=2)
    ax.add_patch(arc_arc_C)

    ax.plot([0.000], [-0.000], 'ko', markersize=4.8, zorder=4)

    ax.text(2.856, 2.336, r'f(x) = ax$^2$ + bx + c', fontsize=16.8, ha='left', va='center', zorder=5)

    ax.text(1.422, 2.472, r'm', fontsize=15.2, ha='center', va='center', zorder=5)

    ax.text(0.174, 1.836, r'a', fontsize=14.4, ha='left', va='center', zorder=5)

    ax.text(-1.350, 1.636, r'b', fontsize=15.2, ha='center', va='center', zorder=5)

    ax.text(-0.174, 0.722, r'n', fontsize=14.4, ha='right', va='center', zorder=5)

    ax.text(0.259, 0.596, r'A', fontsize=15.2, ha='center', va='center', zorder=5)

    ax.text(-1.475, 1.288, r'B', fontsize=15.2, ha='center', va='center', zorder=5)

    ax.text(-0.750, -0.420, r'C', fontsize=16.8, ha='right', va='center', zorder=5)

    plt.tight_layout()
    plt.savefig('reconstructed_diagram.png', bbox_inches='tight', dpi=300)
    plt.close()
    print('Saved reconstructed_diagram.png')

if __name__ == '__main__':
    draw_diagram()