"""
Matplotlib Python Code Generator for DiagramIR.
"""

from __future__ import annotations
import math
from ..core.models import DiagramIR, ArrowType
from ..solver.geometry_solver import GeometrySolver


class MatplotlibRenderer:
    """
    Renders DiagramIR into a standalone executable Python script using Matplotlib.
    """

    def __init__(self, ir: DiagramIR):
        self.ir = ir

    def render(self) -> str:
        code = []
        code.append("#!/usr/bin/env python3")
        code.append('"""')
        code.append('Standalone Python/Matplotlib recreation generated by MathRecon Engine.')
        code.append('"""')
        code.append("import matplotlib.pyplot as plt")
        code.append("import numpy as np")
        code.append("import matplotlib.patches as patches")
        code.append("import math")
        code.append("")
        code.append("def draw_diagram():")
        code.append("    fig, ax = plt.subplots(figsize=(6.5, 4.8), dpi=300)")
        code.append("    ax.set_aspect('equal')")
        code.append("    ax.axis('off')")
        code.append("")
        
        # Parabolas
        for parab in self.ir.parabolas:
            x_min, x_max = parab.domain
            code.append(f"    # Parabola: {parab.id}")
            code.append(f"    xs = np.linspace({x_min}, {x_max}, {parab.samples})")
            code.append(f"    ys = {parab.a} * (xs**2) + {parab.b} * xs + {parab.c}")
            code.append(f"    ax.plot(xs, ys, color='{parab.color}', linewidth={parab.stroke_width}, zorder=2)")
            
            # Explicit arrowheads pointing outward at both tips
            if parab.arrows in [ArrowType.BOTH, ArrowType.START]:
                code.append(f"    ax.annotate('', xy=(xs[0], ys[0]), xytext=(xs[3], ys[3]),")
                code.append(f"                arrowprops=dict(arrowstyle='-|>', lw={parab.stroke_width}, color='{parab.color}', mutation_scale=16))")
                
            if parab.arrows in [ArrowType.BOTH, ArrowType.END]:
                code.append(f"    ax.annotate('', xy=(xs[-1], ys[-1]), xytext=(xs[-4], ys[-4]),")
                code.append(f"                arrowprops=dict(arrowstyle='-|>', lw={parab.stroke_width}, color='{parab.color}', mutation_scale=16))")
            code.append("")

        # Segments
        for seg in self.ir.segments:
            w_start = GeometrySolver.screen_to_world(seg.start, self.ir.coordinate_system, self.ir.width, self.ir.height, self.ir.padding)
            w_end = GeometrySolver.screen_to_world(seg.end, self.ir.coordinate_system, self.ir.width, self.ir.height, self.ir.padding)
            code.append(f"    # Segment: {seg.id}")
            code.append(f"    ax.plot([{w_start[0]:.3f}, {w_end[0]:.3f}], [{w_start[1]:.3f}, {w_end[1]:.3f}], color='{seg.color}', linewidth={seg.stroke_width}, zorder=2)")
            code.append("")

        # Right angles
        for ra in self.ir.right_angles:
            pts = GeometrySolver.compute_right_angle_box(ra.vertex, ra.arm1_pt, ra.arm2_pt, ra.size)
            w_pts = [GeometrySolver.screen_to_world(p, self.ir.coordinate_system, self.ir.width, self.ir.height, self.ir.padding) for p in pts]
            code.append(f"    # Right Angle: {ra.id}")
            code.append(f"    ax.plot([{w_pts[0][0]:.3f}, {w_pts[1][0]:.3f}, {w_pts[2][0]:.3f}], [{w_pts[0][1]:.3f}, {w_pts[1][1]:.3f}, {w_pts[2][1]:.3f}], color='{ra.color}', linewidth={ra.stroke_width}, zorder=2)")
            code.append("")

        # Arc Angles
        for aa in self.ir.arc_angles:
            w_v = GeometrySolver.screen_to_world(aa.vertex, self.ir.coordinate_system, self.ir.width, self.ir.height, self.ir.padding)
            w_s = GeometrySolver.screen_to_world(aa.start_pt, self.ir.coordinate_system, self.ir.width, self.ir.height, self.ir.padding)
            w_e = GeometrySolver.screen_to_world(aa.end_pt, self.ir.coordinate_system, self.ir.width, self.ir.height, self.ir.padding)
            
            ang_s = math.degrees(math.atan2(w_s[1] - w_v[1], w_s[0] - w_v[0]))
            ang_e = math.degrees(math.atan2(w_e[1] - w_v[1], w_e[0] - w_v[0]))
            t1, t2 = min(ang_s, ang_e), max(ang_s, ang_e)
            if t2 - t1 > 180:
                t1, t2 = t2, t1 + 360
            r_val = (aa.radius / self.ir.width) * (self.ir.coordinate_system.x_range[1] - self.ir.coordinate_system.x_range[0])
            code.append(f"    # Arc Angle: {aa.id}")
            code.append(f"    arc_{aa.id} = patches.Arc(({w_v[0]:.3f}, {w_v[1]:.3f}), {r_val * 2:.3f}, {r_val * 2:.3f}, angle=0, theta1={t1:.1f}, theta2={t2:.1f}, color='{aa.color}', linewidth={aa.stroke_width}, zorder=2)")
            code.append(f"    ax.add_patch(arc_{aa.id})")
            code.append("")

        # Points
        for pt in self.ir.points:
            w_pt = GeometrySolver.screen_to_world((pt.x, pt.y), self.ir.coordinate_system, self.ir.width, self.ir.height, self.ir.padding)
            code.append(f"    ax.plot([{w_pt[0]:.3f}], [{w_pt[1]:.3f}], 'ko', markersize={pt.radius * 1.2}, zorder=4)")
            code.append("")

        # Labels
        anchor_map = {"start": "left", "middle": "center", "end": "right"}
        for lbl in self.ir.labels:
            w_pos = GeometrySolver.screen_to_world((lbl.x, lbl.y), self.ir.coordinate_system, self.ir.width, self.ir.height, self.ir.padding)
            clean_text = lbl.text.replace("^2", "$^2$")
            ha = anchor_map.get(lbl.anchor, "center")
            code.append(f"    ax.text({w_pos[0]:.3f}, {w_pos[1]:.3f}, r'{clean_text}', fontsize={lbl.font_size * 0.8:.1f}, ha='{ha}', va='center', zorder=5)")
            code.append("")

        code.append("    plt.tight_layout()")
        code.append("    plt.savefig('reconstructed_diagram.png', bbox_inches='tight', dpi=300)")
        code.append("    plt.close()")
        code.append("    print('Saved reconstructed_diagram.png')")
        code.append("")
        code.append("if __name__ == '__main__':")
        code.append("    draw_diagram()")
        return "\n".join(code)
