"""
Matplotlib Python Script Generator for acad_visual.
"""

from __future__ import annotations
import math
from ..core.ir import VisualIR
from ..core.primitives import ArrowType
from ..core.coordinate import CoordinateTransformer
from ..geometry.solver import AnalyticalGeometrySolver


class UniversalMatplotlibRenderer:
    """Renders VisualIR into standalone, executable Python Matplotlib scripts."""

    def __init__(self, ir: VisualIR):
        self.ir = ir

    def render(self) -> str:
        cf = self.ir.coordinate_frame
        xmin, xmax = cf.x_range
        ymin, ymax = cf.y_range

        code = [
            "#!/usr/bin/env python3",
            '"""',
            f'Standalone Matplotlib Artwork - {self.ir.title} ({self.ir.subject})',
            'Generated by acad_visual framework.',
            '"""',
            "import matplotlib.pyplot as plt",
            "import numpy as np",
            "import matplotlib.patches as patches",
            "import math",
            "",
            "def draw_diagram():",
            "    fig, ax = plt.subplots(figsize=(6.5, 4.8), dpi=300)",
            "    ax.set_aspect('equal')",
            "    ax.axis('off')",
            f"    ax.set_xlim({xmin:.2f}, {xmax:.2f})",
            f"    ax.set_ylim({ymin:.2f}, {ymax:.2f})",
            ""
        ]

        # Polygons
        for poly in self.ir.polygons:
            w_pts = [CoordinateTransformer.screen_to_world(p, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding) for p in poly.vertices]
            pts_arr = ", ".join([f"[{p[0]:.3f}, {p[1]:.3f}]" for p in w_pts])
            fc = f"'{poly.fill_color}'" if poly.fill_color else "'none'"
            code.append(f"    # Polygon: {poly.id}")
            code.append(f"    poly_{poly.id} = patches.Polygon([{pts_arr}], closed=True, facecolor={fc}, alpha={poly.fill_opacity if poly.fill_color else 1.0}, edgecolor='{poly.stroke_color}', linewidth={poly.stroke_width}, zorder=1)")
            code.append(f"    ax.add_patch(poly_{poly.id})")
            code.append("")

        # Organic shapes
        for org in self.ir.organic_shapes:
            w_pts = [CoordinateTransformer.screen_to_world(p, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding) for p in org.boundary_points]
            pts_arr = ", ".join([f"[{p[0]:.3f}, {p[1]:.3f}]" for p in w_pts])
            code.append(f"    # Organic Shape: {org.name}")
            code.append(f"    poly_{org.id} = patches.Polygon([{pts_arr}], closed=True, facecolor='{org.fill_color}', alpha={org.fill_opacity}, edgecolor='{org.stroke_color}', linewidth={org.stroke_width}, zorder=1)")
            code.append(f"    ax.add_patch(poly_{org.id})")
            code.append("")

        # Conics
        for c in self.ir.conics:
            code.append(f"    # Conic: {c.id}")
            code.append(f"    xs = np.linspace({c.domain[0]}, {c.domain[1]}, {c.samples})")
            code.append(f"    ys = {c.a} * (xs**2) + {c.b} * xs + {c.c}")
            code.append(f"    ax.plot(xs, ys, color='{c.color}', linewidth={c.stroke_width}, zorder=2)")
            if c.arrows in [ArrowType.BOTH, ArrowType.START]:
                code.append(f"    ax.annotate('', xy=(xs[0], ys[0]), xytext=(xs[3], ys[3]), arrowprops=dict(arrowstyle='-|>', lw={c.stroke_width}, color='{c.color}', mutation_scale=16))")
            if c.arrows in [ArrowType.BOTH, ArrowType.END]:
                code.append(f"    ax.annotate('', xy=(xs[-1], ys[-1]), xytext=(xs[-4], ys[-4]), arrowprops=dict(arrowstyle='-|>', lw={c.stroke_width}, color='{c.color}', mutation_scale=16))")
            code.append("")

        # Segments
        for s in self.ir.segments:
            w_start = CoordinateTransformer.screen_to_world(s.start, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding)
            w_end = CoordinateTransformer.screen_to_world(s.end, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding)
            code.append(f"    # Segment: {s.id}")
            code.append(f"    ax.plot([{w_start[0]:.3f}, {w_end[0]:.3f}], [{w_start[1]:.3f}, {w_end[1]:.3f}], color='{s.color}', linewidth={s.stroke_width}, zorder=2)")
            code.append("")

        # Right angles
        for ra in self.ir.right_angles:
            pts = AnalyticalGeometrySolver.compute_right_angle_box(ra.vertex, ra.arm1_pt, ra.arm2_pt, ra.size)
            w_pts = [CoordinateTransformer.screen_to_world(p, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding) for p in pts]
            code.append(f"    ax.plot([{w_pts[0][0]:.3f}, {w_pts[1][0]:.3f}, {w_pts[2][0]:.3f}], [{w_pts[0][1]:.3f}, {w_pts[1][1]:.3f}, {w_pts[2][1]:.3f}], color='{ra.color}', linewidth={ra.stroke_width}, zorder=2)")
            code.append("")

        # Arc Angles
        for aa in self.ir.arc_angles:
            w_v = CoordinateTransformer.screen_to_world(aa.vertex, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding)
            w_s = CoordinateTransformer.screen_to_world(aa.start_pt, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding)
            w_e = CoordinateTransformer.screen_to_world(aa.end_pt, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding)
            ang_s = math.degrees(math.atan2(w_s[1] - w_v[1], w_s[0] - w_v[0]))
            ang_e = math.degrees(math.atan2(w_e[1] - w_v[1], w_e[0] - w_v[0]))
            t1, t2 = min(ang_s, ang_e), max(ang_s, ang_e)
            if t2 - t1 > 180:
                t1, t2 = t2, t1 + 360
            r_val = (aa.radius / (self.ir.width - 2 * self.ir.padding)) * (self.ir.coordinate_frame.x_range[1] - self.ir.coordinate_frame.x_range[0])
            code.append(f"    arc_{aa.id} = patches.Arc(({w_v[0]:.3f}, {w_v[1]:.3f}), {r_val * 2:.3f}, {r_val * 2:.3f}, angle=0, theta1={t1:.1f}, theta2={t2:.1f}, color='{aa.color}', linewidth={aa.stroke_width}, zorder=2)")
            code.append(f"    ax.add_patch(arc_{aa.id})")
            code.append("")

        # Points
        for pt in self.ir.points:
            w_pt = CoordinateTransformer.screen_to_world((pt.x, pt.y), self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding)
            code.append(f"    ax.plot([{w_pt[0]:.3f}], [{w_pt[1]:.3f}], 'ko', markersize={pt.radius * 1.2}, zorder=4)")
            code.append("")

        # Callouts
        for cl in self.ir.callouts:
            w_tp = CoordinateTransformer.screen_to_world(cl.target_point, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding)
            w_lp = CoordinateTransformer.screen_to_world(cl.label_point, self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding)
            code.append(f"    # Callout: {cl.text}")
            code.append(f"    ax.plot([{w_tp[0]:.3f}, {w_lp[0]:.3f}], [{w_tp[1]:.3f}, {w_lp[1]:.3f}], 'k-', linewidth=1.5, zorder=3)")
            code.append(f"    ax.plot([{w_tp[0]:.3f}], [{w_tp[0]:.3f}], 'ko', markersize=4, zorder=4)")
            ha = 'right' if w_lp[0] < w_tp[0] else 'left'
            code.append(f"    ax.text({w_lp[0]:.3f}, {w_lp[1]:.3f}, '{cl.text}', fontsize=14, ha='{ha}', va='center', zorder=5)")
            code.append("")

        # Labels
        anchor_map = {"start": "left", "middle": "center", "end": "right"}
        for lbl in self.ir.labels:
            w_pos = CoordinateTransformer.screen_to_world((lbl.x, lbl.y), self.ir.coordinate_frame, self.ir.width, self.ir.height, self.ir.padding)
            clean_text = lbl.text.replace("^2", "$^2$").replace('"', '\\"').replace("'", "\\'")
            ha = anchor_map.get(lbl.anchor, "center")
            code.append(f"    ax.text({w_pos[0]:.3f}, {w_pos[1]:.3f}, '{clean_text}', fontsize=15, ha='{ha}', va='center', zorder=5)")
            code.append("")

        code.append("    plt.tight_layout()")
        code.append("    plt.savefig('reconstructed_artwork.png', bbox_inches='tight', dpi=300)")
        code.append("    plt.close()")
        code.append("    print('Saved reconstructed_artwork.png')")
        code.append("")
        code.append("if __name__ == '__main__':")
        code.append("    draw_diagram()")
        return "\n".join(code)
